# Generated by Django 4.2.1 on 2023-05-05 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_applicantdetails_emailid_alter_detailadd_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailadd',
            name='name',
            field=models.ForeignKey(blank=True, max_length=25, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
