# Generated by Django 4.2.1 on 2023-05-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_detailadd_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailadd',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
