# Generated by Django 4.2.1 on 2023-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_applicantdetails_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='EmailID',
            field=models.EmailField(max_length=254),
        ),
    ]
