# Generated by Django 4.2.1 on 2023-05-06 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_applicantdetails_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailAddtwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.CharField(max_length=25)),
                ('phoneno', models.CharField(max_length=10)),
                ('linked_in_url', models.URLField(max_length=50)),
                ('job_role', models.CharField(max_length=20)),
                ('resume', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
