# Generated by Django 4.2.1 on 2023-05-06 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_detailaddtwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdetails',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
