# Generated by Django 4.2 on 2023-05-07 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_applicantdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdetails',
            name='ResumeFile',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
