# Generated by Django 4.2 on 2023-05-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_applicantdetails_resumefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantdetails',
            name='user',
        ),
    ]
