# Generated by Django 4.2.1 on 2023-05-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=20)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('age', models.IntegerField()),
                ('Openness', models.IntegerField()),
                ('Conscientiousness', models.IntegerField()),
                ('Extraversion', models.IntegerField()),
                ('Agreeableness', models.IntegerField()),
                ('Neuroticism', models.IntegerField()),
                ('Label', models.CharField(default='Personality Not predicted', max_length=20, null=True)),
            ],
        ),
    ]
